# Generated by Django 5.2 on 2025-04-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.CharField(choices=[('ticket', 'Consumidor Final (Ticket)'), ('factura_afip', 'Factura AFIP')], default='ticket', max_length=20),
        ),
    ]
