# Generated by Django 5.2 on 2025-04-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_tipo_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicion_iva',
            field=models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributista'), ('CF', 'Consumidor Final'), ('EX', 'Exento')], default='CF', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
