# Generated by Django 4.2.1 on 2025-04-25 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_condicion_iva_empresa_cuit_empresa_direccion'),
        ('ventas', '0004_remove_cliente_documento_remove_cliente_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa'),
            preserve_default=False,
        ),
    ]
