# Generated by Django 4.2.1 on 2025-04-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cliente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cuenta_corriente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
