# Generated by Django 5.2 on 2025-04-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_cliente_cuenta_corriente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
