# Generated by Django 4.2.1 on 2025-05-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_cliente_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('MP', 'QR (Mercado Pago)'), ('DN', 'QR (Cuenta DNI)'), ('TJ', 'Tarjeta'), ('TR', 'Transferencia')], default='EF', max_length=2),
        ),
    ]
