# Generated by Django 4.2.1 on 2025-05-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_venta_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cuenta_corriente',
            field=models.BooleanField(default=False),
        ),
    ]
