# Generated by Django 4.2.26 on 2025-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_cliente_cuenta_corriente_pagocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_empresa',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
