# Generated by Django 4.2.26 on 2026-01-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('ventas', '0011_venta_numero_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='caja.cierrecaja'),
        ),
    ]
