# Generated by Django 4.2.26 on 2026-01-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_venta_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
