# Generated by Django 4.2.26 on 2026-02-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_notacredito_detallenotacredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente'),
        ),
    ]
