# Generated by Django 4.2.26 on 2026-02-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_alter_notacredito_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenotacredito',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
