# Generated by Django 4.2.26 on 2026-02-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cierrecaja_saldo_final'),
        ('ventas', '0016_alter_detallenotacredito_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='caja.cierrecaja'),
        ),
    ]
