# Generated by Django 4.2.26 on 2026-02-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_es_empleado'),
        ('ventas', '0018_venta_importe_entregado_venta_vuelto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaArcaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('MP', 'QR (Mercado Pago)'), ('DN', 'QR (Cuenta DNI)'), ('TJ', 'Tarjeta'), ('TR', 'Transferencia')], max_length=2)),
                ('subir_a_arca', models.BooleanField(default=False)),
                ('tipo_comprobante', models.CharField(blank=True, choices=[('cf', 'Consumidor Final'), ('boleta', 'Boleta Común'), ('factura_a', 'Factura A'), ('factura_b', 'Factura B')], max_length=30, null=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteArca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cf', 'Consumidor Final'), ('boleta', 'Boleta Común'), ('factura_a', 'Factura A'), ('factura_b', 'Factura B')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('cae', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_arca', to='ventas.venta')),
            ],
        ),
    ]
