# Generated by Django 4.2.26 on 2026-03-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_es_empleado'),
        ('ventas', '0019_reglaarcapago_comprobantearca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantearca',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('error', 'Error')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reglaarcapago',
            unique_together={('empresa', 'tipo_pago')},
        ),
    ]
