# Generated by Django 4.2.26 on 2026-03-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_alter_comprobantearca_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantearca',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobantearca',
            name='vencimiento_cae',
            field=models.DateField(blank=True, null=True),
        ),
    ]
