# Generated by Django 4.2.26 on 2026-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_comprobantearca_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantearca',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comprobantearca',
            name='ultimo_intento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
