# Generated by Django 4.2.26 on 2026-03-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_comprobantearca_intentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantearca',
            name='procesando',
            field=models.BooleanField(default=False),
        ),
    ]
