# Generated by Django 4.2.26 on 2026-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_comprobantearca_procesando'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
