# Generated by Django 4.2.26 on 2026-03-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0024_detalleventa_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_compra',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
