# Generated by Django 4.2.26 on 2026-03-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_empresa_arca_certificado_empresa_arca_clave_privada_and_more'),
        ('ventas', '0025_detalleventa_precio_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenArca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(default='wsfe', max_length=20)),
                ('modo', models.CharField(default='homologacion', max_length=20)),
                ('token', models.TextField()),
                ('sign', models.TextField()),
                ('expira', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_arca', to='usuarios.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'servicio', 'modo')},
            },
        ),
    ]
