# Generated by Django 4.2.26 on 2026-04-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_tokenarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantearca',
            name='comprobante_asociado_nro',
            field=models.IntegerField(blank=True, help_text='Número del comprobante que se anula', null=True),
        ),
        migrations.AddField(
            model_name='comprobantearca',
            name='comprobante_asociado_pto_vta',
            field=models.IntegerField(blank=True, help_text='Punto de venta del comprobante original', null=True),
        ),
        migrations.AddField(
            model_name='comprobantearca',
            name='comprobante_asociado_tipo',
            field=models.IntegerField(blank=True, help_text='Tipo del comprobante que se anula (para NC)', null=True),
        ),
    ]
