# Generated by Django 4.2.26 on 2026-04-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_comprobantearca_comprobante_asociado_nro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.CharField(choices=[('ticket', 'Consumidor Final (Ticket)'), ('factura_afip', 'Factura AFIP'), ('nc_a', 'Nota de Crédito A'), ('nc_b', 'Nota de Crédito B'), ('nc_c', 'Nota de Crédito C')], default='ticket', max_length=20),
        ),
    ]
