# Generated by Django 4.2.26 on 2026-04-30 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_comprobantearca_comprobante_asociado_nro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantearca',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_arca', to='ventas.venta'),
        ),
    ]
