# Generated by Django 4.2.26 on 2026-04-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_alter_venta_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantearca',
            name='tipo',
            field=models.CharField(choices=[('cf', 'Consumidor Final'), ('boleta', 'Boleta Común'), ('factura_a', 'Factura A'), ('factura_b', 'Factura B'), ('nc_a', 'Nota de Crédito A'), ('nc_b', 'Nota de Crédito B'), ('nc_c', 'Nota de Crédito C')], max_length=30),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.CharField(choices=[('ticket', 'Consumidor Final (Ticket)'), ('factura_afip', 'Factura AFIP')], default='ticket', max_length=20),
        ),
    ]
