# Generated by Django 4.2.26 on 2026-05-16 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0006_empresa_arca_certificado_empresa_arca_clave_privada_and_more'),
        ('caja', '0002_cierrecaja_saldo_final'),
        ('ventas', '0029_alter_comprobantearca_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('proveedor', 'Pago a Proveedor'), ('servicio', 'Servicio (luz, agua, internet)'), ('alquiler', 'Alquiler'), ('sueldo', 'Sueldo/Honorarios'), ('impuesto', 'Impuesto/Tasas'), ('varios', 'Otros Gastos')], default='varios', max_length=20)),
                ('concepto', models.CharField(help_text='Ej: Pago a Distribuidora XYZ', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TR', 'Transferencia'), ('TJ', 'Tarjeta')], default='EF', max_length=2)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='caja.cierrecaja')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egreso de Caja',
                'verbose_name_plural': 'Egresos de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
