# Generated by Django 4.2.26 on 2026-06-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_egresocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.CharField(choices=[('58mm', 'Ticket 58 mm'), ('80mm', 'Ticket 80 mm'), ('a4', 'Hoja A4')], default='80mm', max_length=20),
        ),
    ]
