# Generated by Django 4.2.26 on 2026-06-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_alter_venta_tipo_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantearca',
            name='alicuota_iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 10.5 o 21.0. Si es null usa el default de la empresa.', max_digits=5, null=True),
        ),
    ]
