# Generated by Django 4.2.26 on 2026-08-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0032_comprobantearca_alicuota_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='es_bulto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='unidades_por_bulto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
