# Generated by Django 4.2.26 on 2026-09-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0033_detalleventa_es_bulto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='metros_por_caja',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='metros_totales',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
