# Generated by Django 4.2.26 on 2026-09-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0034_detalleventa_metros_por_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='recargo_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='recargo_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reglaarcapago',
            name='tipo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('MP', 'QR (Mercado Pago)'), ('DN', 'QR (Cuenta DNI)'), ('TJ', 'Tarjeta'), ('TR', 'Transferencia'), ('TJ1', 'Tarjeta 1 pago'), ('TJ3', 'Tarjeta 3 pagos'), ('TJ6', 'Tarjeta 6 pagos')], max_length=3),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('MP', 'QR (Mercado Pago)'), ('DN', 'QR (Cuenta DNI)'), ('TJ', 'Tarjeta'), ('TR', 'Transferencia'), ('TJ1', 'Tarjeta 1 pago'), ('TJ3', 'Tarjeta 3 pagos'), ('TJ6', 'Tarjeta 6 pagos')], default='EF', max_length=3),
        ),
    ]
