# Generated by Django 4.2.26 on 2026-02-02 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_usuario_es_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionImpresoraTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Impresora de Tickets', max_length=100)),
                ('nombre_sistema', models.CharField(help_text='Nombre EXACTO de la impresora en Windows', max_length=200)),
                ('ancho_mm', models.PositiveIntegerField(default=80, help_text='Ancho del papel (58 u 80 mm)')),
                ('cortar_papel', models.BooleanField(default=True, help_text='Enviar comando de corte al finalizar')),
                ('abrir_cajon', models.BooleanField(default=False, help_text='Abrir cajón de dinero al imprimir')),
                ('font_size', models.PositiveIntegerField(default=1, help_text='ESC/POS font size (1 normal)')),
                ('line_spacing', models.PositiveIntegerField(default=30, help_text='Espaciado entre líneas (ESC/POS)')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_impresora_ticket', to='usuarios.empresa')),
            ],
        ),
    ]
