# Generated by Django 4.2.26 on 2026-02-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionimpresoraticket',
            name='datos_empresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionimpresoraticket',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_impresora/'),
        ),
        migrations.AddField(
            model_name='configuracionimpresoraticket',
            name='saludo_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionimpresoraticket',
            name='test_ok',
            field=models.BooleanField(default=False, help_text='Resultado del último test de impresión'),
        ),
        migrations.AddField(
            model_name='configuracionimpresoraticket',
            name='tipo_conexion',
            field=models.CharField(choices=[('usb', 'USB'), ('lan', 'LAN')], default='usb', help_text='Tipo de conexión de la impresora', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracionimpresoraticket',
            name='ultimo_test',
            field=models.DateTimeField(blank=True, help_text='Fecha del último test de impresión', null=True),
        ),
        migrations.AlterField(
            model_name='configuracionimpresoraticket',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está activo, se usará este microservicio'),
        ),
        migrations.AlterField(
            model_name='configuracionimpresoraticket',
            name='nombre',
            field=models.CharField(default='Impresora de Tickets', help_text='Nombre descriptivo de la impresora', max_length=100),
        ),
    ]
