# Generated by Django 4.2.26 on 2026-02-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0002_configuracionimpresoraticket_datos_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionimpresoraticket',
            name='microservicio_url',
            field=models.URLField(blank=True, help_text='URL del microservicio ESC/POS en la PC del cliente', null=True),
        ),
    ]
