# Generated by Django 4.2.26 on 2026-09-23 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0013_producto_metros_cuadrados_por_caja_and_more'),
        ('ventas', '0034_detalleventa_metros_por_caja_and_more'),
        ('usuarios', '0012_empresa_usa_venta_por_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(blank=True, help_text='Para clientes no registrados', max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_empresa', models.PositiveIntegerField(default=1)),
                ('validez_dias', models.PositiveIntegerField(default=7)),
                ('nota', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('anulado', 'Anulado')], default='vigente', max_length=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('empresa', 'numero_empresa')},
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metros_por_caja', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('metros_totales', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('precio_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='presupuestos.presupuesto')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
        ),
    ]
