# Generated by Django 4.2.26 on 2025-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_condicion_iva_empresa_cuit_empresa_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('condicion_iva', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
