# Generated by Django 4.2.26 on 2026-01-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_empresa_activo_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_empleado',
            field=models.BooleanField(default=False, help_text='Si está tildado, necesita abrir caja para vender y tiene restricciones de acceso'),
        ),
    ]
