# Generated by Django 4.2.26 on 2026-03-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_es_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='arca_certificado',
            field=models.FileField(blank=True, null=True, upload_to='arca/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='arca_clave_privada',
            field=models.FileField(blank=True, null=True, upload_to='arca/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='arca_modo',
            field=models.CharField(choices=[('homologacion', 'Homologación'), ('produccion', 'Producción')], default='homologacion', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='arca_punto_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usa_arca',
            field=models.BooleanField(default=False, help_text='Indica si la empresa factura con ARCA'),
        ),
    ]
