# Generated by Django 4.2.26 on 2026-06-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_empresa_formato_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='formato_ticket',
            field=models.CharField(choices=[('80mm', 'Ticket 80mm (térmica)'), ('58mm', 'Ticket 58mm (térmica)'), ('a4', 'Boleta A4')], default='80mm', help_text='Formato del comprobante tipo ticket para esta empresa', max_length=10),
        ),
    ]
