# Generated by Django 4.2.26 on 2026-06-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_empresa_formato_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='arca_alicuota_iva_default',
            field=models.DecimalField(decimal_places=2, default=10.5, help_text='Alícuota de IVA por defecto para comprobantes ARCA (ej: 10.5 o 21.0)', max_digits=5),
        ),
    ]
