# Generated by Django 4.2.26 on 2026-09-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_empresa_arca_alicuota_iva_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='mensaje_aviso',
            field=models.CharField(blank=True, default='💳 El pago del sistema está pendiente. Por favor regularizá.', help_text='Texto que se muestra en el banner de aviso.', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mostrar_aviso',
            field=models.BooleanField(default=False, help_text='Tildar para mostrar el mensaje de aviso a todos los usuarios.'),
        ),
    ]
