# Generated by Django 4.2.26 on 2026-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_empresa_mensaje_aviso_empresa_mostrar_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_aviso',
            field=models.CharField(choices=[('info', '🔵 Informativo (azul)'), ('naranja', '🟠 Atención (naranja)'), ('rojo', '🔴 Urgente (rojo)')], default='naranja', max_length=10, verbose_name='Color del aviso'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='mensaje_aviso',
            field=models.CharField(blank=True, default='💳 El pago del sistema está pendiente. Por favor regularizá.', max_length=255, verbose_name='Mensaje del aviso'),
        ),
    ]
