# Generated by Django 4.2.26 on 2026-09-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_empresa_tipo_aviso_alter_empresa_mensaje_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usa_venta_por_caja',
            field=models.BooleanField(default=False, help_text='Permite utilizar la nueva modalidad de venta por caja y metros cuadrados.', verbose_name='Habilitar venta por caja / m²'),
        ),
    ]
