# Generated by Django 4.2.26 on 2026-10-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_empresa_usa_venta_por_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usa_balanza',
            field=models.BooleanField(default=False, help_text='Envía los precios de productos asignados a la balanza Cuora.', verbose_name='Habilitar sincronización con balanza'),
        ),
    ]
