# Generated by Django 4.2.1 on 2025-05-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aplica_descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_minima_descuento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
