# Generated by Django 4.2.26 on 2025-11-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_condicion_iva_empresa_cuit_empresa_direccion'),
        ('productos', '0004_producto_aplica_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo', 'empresa')},
        ),
    ]
