# Generated by Django 4.2.26 on 2026-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_codigo_alter_producto_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alerta_stock_bajo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo_alerta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
