# Generated by Django 4.2.26 on 2026-07-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_alerta_stock_bajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dias_aviso_vencimiento',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
