# Generated by Django 4.2.26 on 2026-07-07 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_empresa_arca_alicuota_iva_default'),
        ('productos', '0007_producto_dias_aviso_vencimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAvisoVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_fecha_avisada', models.DateField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
            ],
        ),
    ]
