# Generated by Django 4.2.26 on 2026-07-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_controlavisovencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlavisovencimiento',
            name='ultima_fecha_avisada',
        ),
        migrations.AddField(
            model_name='controlavisovencimiento',
            name='ultimo_aviso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
