# Generated by Django 4.2.26 on 2026-08-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_controlavisovencimiento_ultima_fecha_avisada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_por_bulto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_bulto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='vende_por_bulto',
            field=models.BooleanField(default=False),
        ),
    ]
