# Generated by Django 4.2.26 on 2026-08-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_precio_por_bulto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_descuento_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
