# Generated by Django 4.2.26 on 2026-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_precio_descuento_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
