# Generated by Django 4.2.26 on 2026-09-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='metros_cuadrados_por_caja',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Metros cuadrados por caja'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_por_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por m²'),
        ),
        migrations.AddField(
            model_name='producto',
            name='venta_por_caja',
            field=models.BooleanField(default=False, verbose_name='Venta por caja'),
        ),
    ]
