# Generated by Django 4.2.26 on 2026-01-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tamano_hoja', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], default='A4', max_length=10)),
                ('columnas', models.PositiveIntegerField(default=1)),
                ('filas', models.PositiveIntegerField(default=1)),
                ('alto_etiqueta_mm', models.PositiveIntegerField(default=50)),
                ('mostrar_codigo', models.BooleanField(default=True)),
                ('mostrar_precio', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
