# Generated by Django 4.2.26 on 2026-01-09 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_cliente'),
        ('impresion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloimpresion',
            name='alto_etiqueta_mm',
        ),
        migrations.RemoveField(
            model_name='modeloimpresion',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='modeloimpresion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='borde_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_impresion', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='fondo_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='orientacion',
            field=models.CharField(choices=[('portrait', 'Vertical'), ('landscape', 'Horizontal')], default='portrait', max_length=10),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='padding',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='precio_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='precio_negrita',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='precio_tamano',
            field=models.PositiveIntegerField(default=28),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='titulo_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='titulo_negrita',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='titulo_tamano',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
