# Generated by Django 4.2.26 on 2026-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0002_remove_modeloimpresion_alto_etiqueta_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloimpresion',
            name='alineacion_horizontal',
            field=models.CharField(choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='alineacion_vertical',
            field=models.CharField(choices=[('start', 'Arriba'), ('center', 'Centro'), ('end', 'Abajo')], default='center', max_length=10),
        ),
    ]
