# Generated by Django 4.2.26 on 2026-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0003_modeloimpresion_alineacion_horizontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloimpresion',
            name='alineacion_horizontal',
            field=models.CharField(choices=[('flex-start', 'Izquierda'), ('center', 'Centro'), ('flex-end', 'Derecha')], default='center', max_length=20),
        ),
        migrations.AlterField(
            model_name='modeloimpresion',
            name='alineacion_vertical',
            field=models.CharField(choices=[('flex-start', 'Arriba'), ('center', 'Centro'), ('flex-end', 'Abajo'), ('space-between', 'Distribuido')], default='center', max_length=20),
        ),
    ]
