# Generated by Django 4.2.26 on 2026-01-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0004_alter_modeloimpresion_alineacion_horizontal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloimpresion',
            name='barcode_alto',
            field=models.PositiveIntegerField(default=40, help_text='Alto del código de barras en px'),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='barcode_ancho',
            field=models.PositiveIntegerField(default=120, help_text='Ancho del código de barras en px'),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='barcode_mostrar_texto',
            field=models.BooleanField(default=False, help_text='Mostrar el código debajo del barcode'),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='mostrar_barcode',
            field=models.BooleanField(default=False),
        ),
    ]
