# Generated by Django 4.2.26 on 2026-01-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_es_empleado'),
        ('impresion', '0005_modeloimpresion_barcode_alto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del modelo de etiqueta', max_length=100)),
                ('ancho_mm', models.PositiveIntegerField(choices=[(58, '58mm'), (80, '80mm')], default=58, help_text='Ancho de la etiqueta en mm')),
                ('alto_mm', models.PositiveIntegerField(default=44, help_text='Alto de la etiqueta en mm. Puede ajustarse dinámicamente según contenido')),
                ('margen_superior', models.PositiveIntegerField(default=2, help_text='Márgen superior en mm')),
                ('margen_inferior', models.PositiveIntegerField(default=2, help_text='Márgen inferior en mm')),
                ('margen_izquierdo', models.PositiveIntegerField(default=2, help_text='Márgen izquierdo en mm')),
                ('margen_derecho', models.PositiveIntegerField(default=2, help_text='Márgen derecho en mm')),
                ('fondo_color', models.CharField(default='#FFFFFF', help_text='Color de fondo de la etiqueta', max_length=20)),
                ('borde_color', models.CharField(default='#000000', help_text='Color del borde de la etiqueta', max_length=20)),
                ('padding', models.PositiveIntegerField(default=2, help_text='Padding interno de la etiqueta en px')),
                ('mostrar_nombre', models.BooleanField(default=True, help_text='Mostrar nombre del producto')),
                ('nombre_tamano', models.PositiveIntegerField(default=10, help_text='Tamaño del texto del nombre en px')),
                ('nombre_negrita', models.BooleanField(default=True, help_text='Nombre en negrita')),
                ('mostrar_precio', models.BooleanField(default=True, help_text='Mostrar precio del producto')),
                ('precio_tamano', models.PositiveIntegerField(default=12, help_text='Tamaño del texto del precio en px')),
                ('precio_negrita', models.BooleanField(default=True, help_text='Precio en negrita')),
                ('mostrar_barcode', models.BooleanField(default=False, help_text='Incluir código de barras en la etiqueta')),
                ('barcode_ancho', models.PositiveIntegerField(default=120, help_text='Ancho del código de barras en px')),
                ('barcode_alto', models.PositiveIntegerField(default=40, help_text='Alto del código de barras en px')),
                ('barcode_mostrar_texto', models.BooleanField(default=False, help_text='Mostrar el código debajo del barcode')),
                ('usar_microservicio', models.BooleanField(default=True, help_text='Si la impresora es USB, usar microservicio para impresión automática')),
                ('activo', models.BooleanField(default=True, help_text='Si el modelo está activo y disponible')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_etiquetas', to='usuarios.empresa')),
            ],
        ),
    ]
