# Generated by Django 4.2.26 on 2026-02-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0006_modeloetiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloetiqueta',
            name='alto_mm',
            field=models.PositiveIntegerField(default=0, help_text='0 = alto automático según contenido'),
        ),
    ]
