# Generated by Django 4.2.26 on 2026-08-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0007_alter_modeloetiqueta_alto_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloimpresion',
            name='precio_secundario_color',
            field=models.CharField(default='#555555', max_length=20),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='precio_secundario_negrita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modeloimpresion',
            name='precio_secundario_tamano',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
