# Generated by Django 4.2.26 on 2026-10-05 23:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0013_empresa_usa_balanza'),
        ('productos', '0013_producto_metros_cuadrados_por_caja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteBalanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Agente local', max_length=100)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_latido', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Balanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion_equipo', models.PositiveSmallIntegerField(default=1, help_text='Número de equipo (0-99). NO es una IP.', validators=[django.core.validators.MaxValueValidator(99)])),
                ('tipo_conexion', models.CharField(choices=[('red', 'Red (WiFi/Ethernet, TCP)'), ('usb', 'USB (puerto COM)')], default='red', max_length=5)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('puerto', models.PositiveIntegerField(default=10001)),
                ('puerto_com', models.CharField(blank=True, help_text='Ej: COM3 o /dev/ttyUSB0', max_length=20)),
                ('decimales_precio', models.PositiveSmallIntegerField(choices=[(0, 'Sin decimales'), (2, '2 decimales')], default=0)),
                ('sector_por_defecto', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('activa', models.BooleanField(default=True)),
                ('ultima_comunicacion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_estado', models.CharField(blank=True, max_length=80)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balanzas', to='balanzas.agentebalanza')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBalanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('balanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='balanzas.balanza')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_balanzas', to='productos.producto')),
            ],
            options={
                'unique_together': {('balanza', 'plu'), ('balanza', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='CambioBalanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('alta', 'Alta/modificación completa'), ('precio', 'Cambio de precio'), ('baja', 'Baja')], max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('tipo_venta', models.CharField(default='U', max_length=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('error_detalle', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('sincronizado_en', models.DateTimeField(blank=True, null=True)),
                ('balanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='balanzas.balanza')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['balanza', 'estado'], name='balanzas_ca_balanza_1d7b0a_idx')],
            },
        ),
    ]
