# Generated by Django 4.2.26 on 2026-10-06 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanza',
            name='formato_etiqueta',
            field=models.CharField(default='20PPPPIIIIII', help_text='Código de barras de la etiqueta/ticket (12 caracteres, sin dígito verificador). P = PLU, I = importe. Debe coincidir con lo configurado en la balanza. Ej: 20PPPPIIIIII', max_length=12, validators=[django.core.validators.RegexValidator('^[0-9PIBCSA]{12}$', 'Deben ser 12 caracteres: dígitos fijos y letras P, I, B, C, S, A.')]),
        ),
    ]
